### ISSUE TITLE
Enabled/disabled Module Name on all views

### ISSUE THREAD

**Issue by sjelfull** [diemer/lovely_sorted_addons#1]
Your sorting is being applied to any addon view, eg. inside the Field Editor module. 

See screenshot:
![screenshot_03 05 13_14_22](https://f.cloud.github.com/assets/10508/458806/1da4418c-b3ec-11e2-89f2-5d152105c4f2.png)

**Comment by diemer** [comment]
Hey Fred,

I had actually noticed that the other day too and pushed a fix to github.

Version 1.0.1 fixes that issue.

Thanks for the email though!

**Comment by sjelfull** [comment]
Awesome! And thanks for the addon, this has been a really annoying thing forever, but you actually went and fixed it :+1:
