### ISSUE TITLE
error message in cp

### ISSUE THREAD

**Issue by designingit** [diemer/lovely_sorted_addons#2]
Hi,

I am running 2.5.5 locally and noticed this error message with lovely sorted addons:

http://cl.ly/image/3s0r1D2a3N0x

I am using std add ons such as wygwam, edit field, playa, matrix and also transcribe. 

Florian

**Comment by diemer** [comment]
Thanks! I'll take a look at that. Are you running 1.0.0 or 1.0.1 of LSA?

**Comment by designingit** [comment]
1.0.1

Dan Diemer wrote:

> Thanks! I'll take a look at that. Are you running 1.0.0 or 1.0.1 of LSA?

**Comment by diemer** [comment]
I'm having trouble replicating this. By "edit field" do you mean Field
Editor? If so what version?

**Comment by designingit** [comment]
this.. http://mightybigrobot.com/products/detail/field-editor

the newest version

Dan Diemer wrote:

> I'm having trouble replicating this. By "edit field" do you mean Field
> Editor? If so what version?
> 
> On Sun, May 5, 2013 at 11:13 AM, designingit

**Comment by diemer** [comment]
Curious. I also have the latest installed and couldn't trigger that error.
Regardless, I did just push a release (1.0.3) that should handle that
error. Try it out and let me know if you still have problems.
