### ISSUE TITLE
Extensions page breaks in 2.8

### ISSUE THREAD

**Issue by dreadfullyposh** [diemer/lovely_sorted_addons#5]
When using the add-on in 2.8, the extensions page doesn't show any addons. It looks like the markup has changed for the page and therefore might not be getting processed correctly.

**Comment by CreateSean** [comment]
I, too, am having the same issue. Any chance this can be fixed to work with 2.8.x

**Comment by diemer** [comment]
Yah, I'll get this fixed up in the next day or so.

**Comment by diemer** [comment]
I've got a fix in place for this, just gotta make sure it doesn't break backward compatibility. I'll be testing that tomorrow and if all is good, I'll push the new version.

**Comment by CreateSean** [comment]
Excellent, looking forward to the new release.

**Comment by diemer** [comment]
Allllllllllll fixed
